[lib]
name = "greprslib"
version = "0.1.0"
authors = ["blueburningcoder <f.karg10@gmail.com>"]

[package]
name = "greprsbin"
version = "0.1.0"
authors = ["blueburningcoder <f.karg10@gmail.com>"]

[dependencies]
